### ISSUE TITLE
Error when running main.py 

### ISSUE THREAD

**Issue by imaxpayne** [cbfinn/maml#1]
Hi,  I was trying to test the model on Omniglot dataset, I downloaded and processed the dataset as instructed, but when I run main.py using the Usage Instruction for 5-way 1-shot omniglot and 20-way 1-shot omniglot  , I encounter the following error message:

```
Generating filenames
Generating image processing ops
Batching images
Manipulating image data to be right shape
Generating filenames
Traceback (most recent call last):
  File "main.py", line 350, in <module>
    main()
  File "main.py", line 280, in main
    image_tensor, label_tensor = data_generator.make_data_tensor(train=False)
  File "/home/rvl224/maml/data_generator.py", line 99, in make_data_tensor
    sampled_character_folders = random.sample(folders, self.num_classes)
  File "/home/rvl224/anaconda2/lib/python2.7/random.py", line 323, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population

```

It seems like the length of folders in
`sampled_character_folders = random.sample(folders, self.num_classes)`
become zero when generating the `metaval_input_tensors` in `main.py`

I am using ubuntu14.04, anaconda python 2.7*, and tf 1.0, with latest numpy

Really appreciate for open sourcing this amazing work,
Max.

**Comment by cbfinn** [comment]
It seems like it is not finding the images, causing `folders` to be an empty list. It looks for the images in `./data/omniglot_resized` (on this line of code https://github.com/cbfinn/maml/blob/master/data_generator.py#L40)

Are you calling the code from the maml/ directory? e.g. `python main.py`
Can you see if the `folders` is indeed an empty list?

**Comment by imaxpayne** [comment]
Yes, I was running` main.py` from `maml/` directory,
I found that when I run` main.py`, it was able to execute the line https://github.com/cbfinn/maml/blob/master/main.py#L272, and generate the tensor shape (32, 10, 784) (32, 10, 784) for` image_tensor, label_tensor` respectively , and the `folders` in https://github.com/cbfinn/maml/blob/master/data_generator.py#L95 was not a empty list.

but when it continue and execute the line https://github.com/cbfinn/maml/blob/master/main.py#L280, it print out the error message I describe above, and the` folders` in https://github.com/cbfinn/maml/blob/master/data_generator.py#L95  was empty list when I print `len(folders)`, it shows zero.

So it was able to generate `image_tensor` when calling `data_generator.make_data_tensor()`, but not `data_generator.make_data_tensor(train=False) `

Thank you for your response, really looking forward to test and play with the model !  
Max.

**Comment by cbfinn** [comment]
Ah, okay. Make sure you download both images_background and images_evaluation from the omniglot website, and put them in the same directory (and run the preprocessing for all images)

That should solve your problem. (It seems to be that there are <= 1200 character classes in the dataset that you downloaded)

If this solves your issue, then I will clarity the Omniglot data instructions.

**Comment by imaxpayne** [comment]
Yes!  This solves the problem. Thank you very much.

**Comment by e-271** [comment]
Hi, I am having a similar problem. I can't find any dataset to download on the omniglot website, so I got them from here: https://github.com/brendenlake/omniglot

Where can we get the right dataset?

**Comment by ucasiggcas** [comment]
Dear,

How to start the project ?

I just want to test the regression using MAML in predicting the price of stock.

Any help?
