### ISSUE TITLE
cannot create a tensor larger than 2GB

### ISSUE THREAD

**Issue by zfengwei** [cbfinn/maml#3]
When I run python main.py --datasource=omniglot --metatrain_iterations=40000 --meta_batch_size=16 --update_batch_size=5 --num_classes=20 --update_lr=0.1 --num_updates=5 --logdir=logs/omniglot20way5shot/, it raised a ValueError: Cannot create a tensor proto whose content is larger than 2GB. I'd like to ask how to train the model on omniglot, 20-way, 5-shot?

**Comment by cbfinn** [comment]
For the omniglot experiments, I trained on 1-shot and evaluated on 5-shot.

To evaluate on 5-shot using a model trained on 1-shot, use the flags `--train=False --update_batch_size=5 --train_update_batch_size=1`

If you want to train a model on 5-shot, you can also reduce the meta-batch size so that it fits in memory.

**Comment by zfengwei** [comment]
OK, I see. Thank you very much! I reduced the meta_batch_size to 1 and num_updates to 1, but it still raised the same error. Also, I did these experiments several times and I got different results. It seems that there are some random factors, such as initialization of the network. How much of these random factors will have an effect on the results?

**Comment by cbfinn** [comment]
Generally, I have found the experiments to be fairly repeatable at
convergence (though learning speed at the beginning of training may vary).

What GPU are you using? You need a GPU with sufficient memory. I used a
Titan X, which has 12 GB.

**Comment by zfengwei** [comment]
I also use a GPU with 12GB. It seems that this is the restriction of tensorflow. It cannot create a tensor larger than 2GB.

**Comment by cbfinn** [comment]
Ok. Is this the input tensor that the error is referring to? I don't think
that you should be hitting 2 GB with the input tensor with a meta-batch
size of 1. I would estimate that for 20-way classification, a meta-batch
size of 1, 5-shot, it should be 20*(5+15)*(80*80*3)*32 bits = 0.03 GB.

[The 5+15 is 5 images for calculating the gradient step and 15 images for
the post-update evaluation.]


Can you provide more information on the error?

**Comment by cbfinn** [comment]
If you want to try decreasing the 15 (to as low as 1), you change this line:
https://github.com/cbfinn/maml/blob/master/main.py#L249

**Comment by zfengwei** [comment]
Thank you for your reply! The error is as follows:
`Generating filenames
Traceback (most recent call last):
  File "main.py", line 350, in <module>
    main()
  File "main.py", line 272, in main
    image_tensor, label_tensor = data_generator.make_data_tensor()
  File "/home/maml/data_generator.py", line 103, in make_data_tensor
    filename_queue = tf.train.string_input_producer(tf.convert_to_tensor(all_filenames), shuffle=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 106, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1219, in __init__
    "Cannot create a tensor proto whose content is larger than 2GB.")
ValueError: Cannot create a tensor proto whose content is larger than 2GB.`

**Comment by zfengwei** [comment]
Thank you for your reply! I think the error is caused by this line:
[https://github.com/cbfinn/maml/blob/master/data_generator.py#L86](url)
I reduced the num_total_batches to 100000 and I can train the model on 5-shot.

**Comment by cbfinn** [comment]
Ah, okay. Thanks for letting me know!
