### ISSUE TITLE
Any tips to speed up training process?

### ISSUE THREAD

**Issue by dragen1860** [cbfinn/maml#31]
The overall training speed seems to be a little bit slow.
Any tip to speed up ? such as enlarger task num?

**Comment by cbfinn** [comment]
I haven't tried much to speed it up. You could try loading the dataset into memory and use feed_dict instead of the current data loading scheme, or playing around with the hyperparameters.

**Comment by cbfinn** [comment]
Using the first-order approximation through the stop_grad flag also speeds up the code, with a marginal hit to performance.
