### ISSUE TITLE
A question about mini-imagenet 

### ISSUE THREAD

**Issue by imaxpayne** [cbfinn/maml#4]
Hi, I am a little confused about the image.zip that mentioned in https://github.com/cbfinn/maml/blob/master/data/miniImagenet/proc_images.py#L4, is it from ILSRVC2012_img_train.tar ? 

many thanks,
Max

**Comment by cbfinn** [comment]
Sorry this is unclear. I got the dataset from Ravi & Larochelle '17. If you email Sachin, he should be able to help.

**Comment by cbfinn** [comment]
I updated the instructions in proc_images.py

**Comment by imaxpayne** [comment]
Thank you! I will contact him via email.

**Comment by jongchyisu** [comment]
Hi Chelsea,

Sorry for opening this issue again, but in the csv files from Sachin's GitHub,  I can't find some of the images in the imagenet by the ID. For example, the first training image is  n0153282900000005.jpg,n01532829
but there is no 5.JPG in 
http://www.image-net.org/api/text/imagenet.synset.geturls.getmapping?wnid=n01532829
How did you solve this issue? Thank you very much!

**Comment by cbfinn** [comment]
@jongchyisu You should contact Sachin via email.

**Comment by jongchyisu** [comment]
Yes I just sent him an email.

**Comment by tonysy** [comment]
@jongchyisu  Hi, I have sent email to Sachin, but got no response, could you share the solution to this problem? Thanks a lot.

**Comment by havaeimo** [comment]
I also sent him an emial and there was no response. It would be great if you could provide that dataset. 
@cbfinn

**Comment by lmzintgraf** [comment]
Dear Chelsea,

following up on this discussion - In your paper you say that the split is 64 train / 12 validation / 24 test classes. The original split (https://github.com/twitter/meta-learning-lstm/tree/master/data/miniImagenet) is 64/16/20 though. Is that just a typo, or did you use a different split?

If anybody is still looking for the dataset, I found this source: https://github.com/dragen1860/LearningToCompare-Pytorch/issues/4

**Comment by cbfinn** [comment]
Yes, it is a typo.
